#python
import os,time,re,string

##re patterns
dig=re.compile(r'([0-9|\.|\-]+)')
unit=re.compile(r'Freq \[(\w+)\]',re.I)

##Unit to digitial
dict_unit = {
     'GHZ':1e9,
     'MHZ':1e6,
     'KHZ':1e3,
     'HZ' :1
}

version="csv2spectre ver0.0"
file_header = "; S-parameter data file 'sp.data'\n"
file_header+= "; Datafile type: Spectre\n"
file_header+= "; Generated by %s at %s\n" %(version,time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))) 
file_header+= "\n"
file_header+= "reference resistance\n"
file_header+= "        port1=50   ; is port p1\n"
file_header+= "        port2=50   ; is port p2\n"
file_header+= "format  freq:    s11(real,imag)    s12(real,imag)\n"
file_header+= "                 s21(real,imag)    s22(real,imag)\n"
file_header+= "\n"
one_freq_sp_tpl ="%f:    %s, %s        %s,%s\n"
one_freq_sp_tpl+=" "*15
one_freq_sp_tpl+="       %s, %s        %s,%s\n"
rm_file=open('re.csv','r')
im_file=open('im.csv','r')
sp_file=open('sp.data','wb+')
rm=rm_file.read().split("\n")
im=im_file.read().split("\n")
s_para=[]
for line,eachline in enumerate(rm):
  if eachline=='':
		break
	if line!=0:
	  rm_data = dig.findall(rm[line])
	  im_data = dig.findall(im[line])
	  temp = []
	  temp.append(float(rm_data[0])*unit_factor)
	  temp.extend([rm_data[1],im_data[1],rm_data[2],im_data[2],rm_data[3],im_data[3],rm_data[4],im_data[4]])
	  s_para.append(temp)
	else:
		freq_unit=unit.findall(eachline)[0]
		unit_factor = dict_unit[freq_unit.upper()]
to_write = file_header
for each in s_para:
	to_write+= one_freq_sp_tpl %(each[0],each[1],each[2],each[3],each[4],each[5],each[6],each[7],each[8])
sp_file.write(to_write)
rm_file.close()
im_file.close()
sp_file.close()
		
